version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
      - mysql
    links:
      - php
    networks:
      - laravel
  php:
    container_name: php
    build:
      context: ./
      dockerfile: php/Dockerfile
    restart: always
    volumes:
      - ./www:/var/www
    networks:
      - laravel
    links:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
    driver: local

networks:
  laravel: