version: "3.9"
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - php
  php:
    container_name: php
    build:
      context: ./
      dockerfile: php/Dockerfile
    restart: always
    volumes:
      - ./www:/var/www
    links:
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
    driver: local